language: android
env:
  global:
    - secure: VffBwEKi8v0WrJC2AFu8H5y9wl44ClJEsmMinQS5TSRTY+o0oeZ6erliGaWjmUqyU0DYUhkxHilyn41OeKTHI+wbBvdJx8vRCe/B+R5RFNDBkVClMViE8IjicMSwOyNQ4tW/rczSBB/iNAZ3xjBk+HZaf5xZkEqsmLgswwAWXmk=
    - secure: PsV548pDm8GL7Fv1uhlg8Oqyl+u6Kt6PwECWxoMiOh8VkJCd3KpAZDB3hIf3v+8JzG8G7co4Cg3Wggcu/q2L5CY3+DSkEnDEpFCfFG9+3NKEe336GGJrGTV7oNUmudrNPBGRUdkLafBvKNKcwOhCoSepFcjFLbdDLgMDbIxvaJU=
android:
  components:
    - platform-tools
    - tools
    - build-tools-21.1.1
    - android-23
    - extra
    - addon-google_apis-google-23
    - sys-img-x86_64-addon-google_apis-google-23
sudo: false
cache:
  directories:
    - node_modules
    - www/lib
before_install:
  - nvm install 4.2
  - nvm use 4.2
install:
  - npm install
  - npm link
before_script:
  - android list targets
  - echo no | android create avd --force -n android-6 -t "Google Inc.:Google APIs:23" --tag google_apis
script:
  - ionic platform add android
  - gulp test:integration:travis
